name = "Fountain"
grammar = "fountain"
path_suffixes = ["fountain"]
soft_wrap = "editor_width"

# Treat notes as a block comment pair so Cmd+/ toggles [[ … ]]
block_comments = [["[[", "]]"]]
autoclose_before = ";:.,=}])>` \n\t\""
brackets = [
    { start = "[[", end = "]]", close = true, newline = false },
    { start = "(", end = ")", close = true, newline = false },
]
